apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: nodejs-template-binding
spec:
  params:
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-repo-name
    value: $(body.repository.name)